/// Flutter icons RentingApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RentingApp
///      fonts:
///       - asset: fonts/RentingApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RentingApp {
  RentingApp._();

  static const _kFontFam = 'RentingApp';
  static const _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alipay = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_low = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broken = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_right = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_expand = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer_service = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gender = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData law_file = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightning = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_on = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_file = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_scan = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData questionnaire = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suitcase = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_up = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vertical_dots = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wechat = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work_list = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData write = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
